export const countries = {
  Peru: 'peruvian',
  Brazil: 'brazilian',
  Libya: 'libyan',
  'San Marino': 'sammarinese',
  Thailand: 'thai',
  Malaysia: 'malaysian',
  Paraguay: 'paraguayan',
  Namibia: 'namibian',
  Slovakia: 'slovak',
  China: 'chinese',
  Honduras: 'honduran',
  Uganda: 'ugandan',
  Indonesia: 'indonesian',
  'South Georgia and the South Sandwich Islands': 'south georgia and the south sandwich islander',
  Yemen: 'yemeni',
  Azerbaijan: 'azerbaijani',
  Israel: 'israeli',
  Singapore: 'singaporean',
  'United Arab Emirates': 'emirati',
  'Bolivia (Plurinational State of)': 'bolivian',
  Ireland: 'irish',
  'Central African Republic': 'central african',
  'French Polynesia': 'french polynesian',
  Grenada: 'grenadian',
  'Guinea-Bissau': 'guinea-bissauan',
  Nepal: 'nepalese',
  Panama: 'panamanian',
  'Burkina Faso': 'burkinabe',
  Cambodia: 'cambodian',
  Uzbekistan: 'uzbekistani',
  Anguilla: 'anguillian',
  'Korea (Republic of)': 'south korean',
  Curaçao: 'curaçaoan',
  'Wallis and Futuna': 'wallis and futuna islander',
  Myanmar: 'burmese',
  Egypt: 'egyptian',
  Gambia: 'gambian',
  'Saudi Arabia': 'saudi arabian',
  Argentina: 'argentinean',
  Canada: 'canadian',
  Montenegro: 'montenegrin',
  'United States of America': 'usa',
  'Cook Islands': 'cook islander',
  Macao: 'macanese',
  'Cocos (Keeling) Islands': 'cocos islander',
  'Saint Lucia': 'saint lucian',
  Cyprus: 'cypriot',
  Iceland: 'icelander',
  "Côte d'Ivoire": 'ivorian',
  Bangladesh: 'bangladeshi',
  Bhutan: 'bhutanese',
  'Saint Kitts and Nevis': 'kittian and nevisian',
  Finland: 'finnish',
  'Macedonia (the former Yugoslav Republic of)': 'macedonian',
  Qatar: 'qatari',
  Sudan: 'sudanese',
  'Isle of Man': 'manx',
  Latvia: 'latvian',
  'Timor-Leste': 'east timorese',
  'Sao Tome and Principe': 'sao tomean',
  Sweden: 'swedish',
  Martinique: 'martinican',
  'Sierra Leone': 'sierra leonean',
  'South Africa': 'south african',
  'Tanzania, United Republic of': 'tanzanian',
  'Costa Rica': 'costa rican',
  'Iran (Islamic Republic of)': 'iranian',
  'Dominican Republic': 'dominican',
  Nigeria: 'nigerian',
  'Palestine, State of': 'palestinian',
  'Bosnia and Herzegovina': 'bosnian, herzegovinian',
  'Cayman Islands': 'caymanian',
  Maldives: 'maldivan',
  Japan: 'japanese',
  Chad: 'chadian',
  Guinea: 'guinean',
  Madagascar: 'malagasy',
  Italy: 'italian',
  Jordan: 'jordanian',
  Liechtenstein: 'liechtensteiner',
  Mongolia: 'mongolian',
  Tonga: 'tongan',
  Ecuador: 'ecuadorean',
  Guam: 'guamanian',
  Kuwait: 'kuwaiti',
  Kyrgyzstan: 'kirghiz',
  Mauritius: 'mauritian',
  'Åland Islands': 'ålandish',
  Bahrain: 'bahraini',
  Mexico: 'mexican',
  Poland: 'polish',
  Chile: 'chilean',
  Djibouti: 'djibouti',
  Ethiopia: 'ethiopian',
  Mauritania: 'mauritanian',
  "Korea (Democratic People's Republic of)": 'north korean',
  Swaziland: 'swazi',
  Aruba: 'aruban',
  Austria: 'austrian',
  Haiti: 'haitian',
  Portugal: 'portuguese',
  Vanuatu: 'ni-vanuatu',
  'Christmas Island': 'christmas island',
  Colombia: 'colombian',
  Cuba: 'cuban',
  'French Guiana': 'french guianese',
  Afghanistan: 'afghan',
  'Brunei Darussalam': 'bruneian',
  Jamaica: 'jamaican',
  'Moldova (Republic of)': 'moldovan',
  France: 'french',
  Kenya: 'kenyan',
  Oman: 'omani',
  Albania: 'albanian',
  'Cabo Verde': 'cape verdian',
  Turkey: 'turkish',
  Zimbabwe: 'zimbabwean',
  Algeria: 'algerian',
  Niger: 'nigerien',
  Hungary: 'hungarian',
  Spain: 'spanish',
  Germany: 'german',
  Guatemala: 'guatemalan',
  Mozambique: 'mozambican',
  Palau: 'palauan',
  Lesotho: 'mosotho',
  'Marshall Islands': 'marshallese',
  Suriname: 'surinamer',
  Guyana: 'guyanese',
  'Sri Lanka': 'sri lankan',
  Lebanon: 'lebanese',
  Mayotte: 'mahoran',
  Samoa: 'samoan',
  'Solomon Islands': 'solomon islander',
  Denmark: 'danish',
  Kiribati: 'i-kiribati',
  Switzerland: 'swiss',
  Lithuania: 'lithuanian',
  Somalia: 'somali',
  'Norfolk Island': 'norfolk islander',
  Taiwan: 'taiwanese',
  Ghana: 'ghanaian',
  'New Zealand': 'new zealander',
  Senegal: 'senegalese',
  Togo: 'togolese',
  Zambia: 'zambian',
  Belarus: 'belarusian',
  'Saint Vincent and the Grenadines': 'saint vincentian',
  'El Salvador': 'salvadoran',
  Norway: 'norwegian',
  Malta: 'maltese',
  Nicaragua: 'nicaraguan',
  Australia: 'australian',
  Luxembourg: 'luxembourger',
  Pakistan: 'pakistani',
  'Saint Helena, Ascension and Tristan da Cunha': 'saint helenian',
  'Turks and Caicos Islands': 'turks and caicos islander',
  'Western Sahara': 'sahrawi',
  Belgium: 'belgian',
  Eritrea: 'eritrean',
  Seychelles: 'seychellois',
  'Antigua and Barbuda': 'antiguan, barbudan',
  Liberia: 'liberian',
  Tuvalu: 'tuvaluan',
  Bermuda: 'bermudian',
  Cameroon: 'cameroonian',
  'Saint Pierre and Miquelon': 'saint-pierrais',
  Ukraine: 'ukrainian',
  Georgia: 'georgian',
  Netherlands: 'dutch',
  Mali: 'malian',
  Niue: 'niuean',
  'Puerto Rico': 'puerto rican',
  'United Kingdom of Great Britain and Northern Ireland': 'british',
  Armenia: 'armenian',
  Greenland: 'greenlandic',
  Kazakhstan: 'kazakhstani',
  Réunion: 'réunionese',
  'Saint Martin (French part)': 'saint martin islander',
  Belize: 'belizean',
  Greece: 'greek',
  'Trinidad and Tobago': 'trinidadian',
  Benin: 'beninese',
  Tajikistan: 'tadzhik',
  'Czech Republic': 'czech',
  India: 'indian',
  "Lao People's Democratic Republic": 'laotian',
  'Syrian Arab Republic': 'syrian',
  Turkmenistan: 'turkmen',
  Botswana: 'motswana',
  'Virgin Islands (British)': 'virgin islander (british)',
  'American Samoa': 'american samoan',
  Guadeloupe: 'guadeloupian',
  'New Caledonia': 'new caledonian',
  'Viet Nam': 'vietnamese',
  Comoros: 'comoran',
  'Micronesia (Federated States of)': 'micronesian',
  Burundi: 'burundian',
  Morocco: 'moroccan',
  'Saint Barthélemy': 'saint barthélemy islander',
  Barbados: 'barbadian',
  'Virgin Islands (U.S.)': 'virgin islander (u.s.)',
  Iraq: 'iraqi',
  'Papua New Guinea': 'papua new guinean',
  'Equatorial Guinea': 'equatorial guinean',
  Gabon: 'gabonese',
  Uruguay: 'uruguayan',
  Monaco: 'monegasque',
  Tunisia: 'tunisian',
  Fiji: 'fijian',
  Rwanda: 'rwandan',
  Angola: 'angolan',
  'Falkland Islands (Malvinas)': 'falkland islander',
  Serbia: 'serbian',
  Slovenia: 'slovenian',
  'Congo (Democratic Republic of the)': 'congolese (democratic republic)',
  Malawi: 'malawian',
  'Venezuela (Bolivarian Republic of)': 'venezuelan',
  Bulgaria: 'bulgarian',
  'Hong Kong': 'hong kongese',
  Gibraltar: 'gibraltar',
  'South Sudan': 'south sudanese',
  Nauru: 'nauruan',
  Pitcairn: 'pitcairn islander',
  'Russian Federation': 'russian',
  Andorra: 'andorran',
  'Faroe Islands': 'faroese',
  Congo: 'congolese',
  Croatia: 'croatian',
  Montserrat: 'montserratian',
  Philippines: 'filipino',
  'Republic of Kosovo': 'kosovar',
  Romania: 'romanian',
  Tokelau: 'tokelauan',
  Bahamas: 'bahamian',
  Estonia: 'estonian',
};
